=== powsybl/powsybl-open-rao/data/crac/crac-io/crac-io-json/src/main/resources/schemas/crac/crac-v2.12.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema#",
  "$id": "resource:/schemas/crac/crac-v2.12.json",
  "title": "CRAC",
  "description": "Contingency list, Remedial Actions and additional Constraints",
  "type": "object",
  "properties": {
    "type": {
      "const": "CRAC"
    },
    "version": {
      "const": "2.12"
    },
    "info": {
      "type": "string"
    },
    "id": {
      "type": "string"
    },
    "name": {
      "type": "string"
    },
    "timestamp": {
      "type": "string"
    },
    "instants": {
      "type": "array",
      "items": {
        "$ref": "../instant/instant-v2.0.json"
      }
    },
    "ra-usage-limits-per-instant": {
      "type": "array",
      "items": {
        "$ref": "../ra-usage-limits-per-instant/ra-usage-limits-per-instant-v2.10.json"
      }
    },
    "contingencies": {
      "type": "array",
      "items": {
        "$ref": "../contingency/contingency-v1.0.json"
      }
    },
    "flowCnecs": {
      "type": "array",
      "items": {
        "items": {
          "$ref": "../flow-cnec/flow-cnec-v2.8.json"
        }
      }
    },
    "angleCnecs": {
      "type": "array",
      "items": {
        "items": {
          "$ref": "../angle-cnec/angle-cnec-v1.4.json"
        }
      }
    },
    "voltageCnecs": {
      "type": "array",
      "items": {
        "items": {
          "$ref": "../voltage-cnec/voltage-cnec-v1.5.json"
        }
      }
    },
    "pstRangeActions": {
      "type": "array",
      "items": {
        "$ref": "../pst-range-action/pst-range-action-v2.8.json"
      }
    },
    "hvdcRangeActions": {
      "type": "array",
      "items": {
        "$ref": "../hvdc-range-action/hvdc-range-action-v2.10.json"
      }
    },
    "injectionRangeActions": {
      "type": "array",
      "items": {
        "$ref": "../injection-range-action/injection-range-action-v2.10.json"
      }
    },
    "counterTradeRangeActions": {
      "type": "array",
      "items": {
        "$ref": "../counter-trade-range-action/counter-trade-range-action-v2.12.json"
      }
    },
    "networkActions": {
      "type": "array",
      "items": {
        "$ref": "../network-action/network-action-v2.10.json"
      }
    }
  },
  "additionalProperties": false,
  "required": [
    "type",
    "version",
    "id",
    "name"
  ]
}

=== powsybl/powsybl-open-rao/data/crac/crac-io/crac-io-json/src/test/resources/retrocompatibility/v2/crac-v2.12.json
{
  "type" : "CRAC",
  "version" : "2.12",
  "info" : "Generated by FARAO http://farao-community.github.io",
  "id" : "exhaustiveCracId",
  "name" : "exhaustiveCracName",
  "timestamp" : "2025-01-01T00:00:00Z",
  "instants" : [ {
    "id": "preventive",
    "kind": "PREVENTIVE"
  }, {
    "id": "outage",
    "kind": "OUTAGE"
  }, {
    "id": "auto",
    "kind": "AUTO"
  }, {
    "id": "toto",
    "kind": "CURATIVE"
  }, {
    "id": "curative",
    "kind": "CURATIVE"
  } ],
  "ra-usage-limits-per-instant" : [ {
    "instant" : "curative",
    "max-ra" : 4,
    "max-topo-per-tso" : {
      "BE" : 6,
      "FR" : 5
    },
    "max-pst-per-tso" : {
      "FR" : 7
    },
    "max-ra-per-tso" : {
      "FR" : 12
    },
    "max-elementary-actions-per-tso" : {
      "FR" : 21
    }
  } ],
  "contingencies" : [ {
    "id" : "contingency1Id",
    "networkElementsIds" : [ "ne1Id" ]
  }, {
    "id" : "contingency2Id",
    "networkElementsIds" : [ "ne2Id", "ne3Id" ]
  } ],
  "flowCnecs" : [ {
    "id" : "cnec1outageId",
    "name" : "cnec1outageId",
    "networkElementId" : "ne4Id",
    "operator" : "operator1",
    "border" : "border1",
    "instant" : "outage",
    "contingencyId" : "contingency1Id",
    "optimized" : true,
    "monitored" : false,
    "reliabilityMargin" : 0.0,
    "thresholds" : [ {
      "unit" : "ampere",
      "min" : -800.0,
      "side" : 1
    } ]
  }, {
    "id" : "cnec1prevId",
    "name" : "cnec1prevId",
    "networkElementId" : "ne4Id",
    "operator" : "operator1",
    "border" : "border1",
    "instant" : "preventive",
    "optimized" : true,
    "monitored" : false,
    "reliabilityMargin" : 0.0,
    "thresholds" : [ {
      "unit" : "ampere",
      "min" : -500.0,
      "side" : 2
    } ]
  }, {
    "id" : "cnec2prevId",
    "name" : "cnec2prevId",
    "networkElementId" : "ne5Id",
    "operator" : "operator2",
    "border" : "border2",
    "instant" : "preventive",
    "optimized" : true,
    "monitored" : false,
    "reliabilityMargin" : 0.0,
    "thresholds" : [ {
      "unit" : "ampere",
      "min" : -800.0,
      "side" : 1
    }, {
      "unit" : "ampere",
      "min" : -800.0,
      "side" : 1
    }, {
      "unit" : "ampere",
      "max" : 1200.0,
      "side" : 2
    }, {
      "unit" : "percent_imax",
      "min" : -0.3,
      "side" : 1
    } ]
  }, {
    "id" : "cnec3autoId",
    "name" : "cnec3autoName",
    "networkElementId" : "ne2Id",
    "operator" : "operator3",
    "border" : "border3",
    "instant" : "auto",
    "contingencyId" : "contingency2Id",
    "optimized" : false,
    "monitored" : true,
    "reliabilityMargin" : 20.0,
    "thresholds" : [ {
      "unit" : "megawatt",
      "max" : 500.0,
      "side" : 1
    } ]
  }, {
    "id" : "cnec3curId",
    "name" : "cnec3curId",
    "networkElementId" : "ne2Id",
    "operator" : "operator3",
    "border" : "border3",
    "instant" : "curative",
    "contingencyId" : "contingency2Id",
    "optimized" : false,
    "monitored" : true,
    "reliabilityMargin" : 20.0,
    "thresholds" : [ {
      "unit" : "megawatt",
      "max" : 500.0,
      "side" : 1
    } ]
  }, {
    "id" : "cnec3prevId",
    "name" : "cnec3prevName",
    "networkElementId" : "ne2Id",
    "operator" : "operator3",
    "border" : "border3",
    "instant" : "preventive",
    "optimized" : false,
    "monitored" : true,
    "reliabilityMargin" : 20.0,
    "thresholds" : [ {
      "unit" : "megawatt",
      "max" : 500.0,
      "side" : 1
    } ]
  }, {
    "id" : "cnec4prevId",
    "name" : "cnec4prevName",
    "networkElementId" : "ne3Id",
    "operator" : "operator4",
    "border" : "border1",
    "instant" : "preventive",
    "optimized" : true,
    "monitored" : true,
    "reliabilityMargin" : 0.0,
    "thresholds" : [ {
      "unit" : "megawatt",
      "max" : 500.0,
      "side" : 1
    } ]
  } ],
  "angleCnecs" : [ {
    "id" : "angleCnecId",
    "name" : "angleCnecName",
    "exportingNetworkElementId" : "eneId",
    "importingNetworkElementId" : "ineId",
    "operator" : "operator1",
    "border" : "border4",
    "instant" : "curative",
    "contingencyId" : "contingency1Id",
    "optimized" : false,
    "monitored" : true,
    "reliabilityMargin" : 0.0,
    "thresholds" : [ {
      "unit" : "degree",
      "min" : -100.0
    } ]
  } ],
  "voltageCnecs" : [ {
    "id" : "voltageCnecId",
    "name" : "voltageCnecName",
    "networkElementId" : "voltageCnecNeId",
    "operator" : "operator1",
    "border" : "border5",
    "instant" : "curative",
    "contingencyId" : "contingency1Id",
    "optimized" : false,
    "monitored" : true,
    "reliabilityMargin" : 0.0,
    "thresholds" : [ {
      "unit" : "kilovolt",
      "min" : 380.0
    } ]
  } ],
  "pstRangeActions" : [ {
    "id" : "pstRange1Id",
    "name" : "pstRange1Name",
    "operator" : "RTE",
    "speed" : 10,
    "onInstantUsageRules" : [ {
      "instant" : "preventive"
    } ],
    "networkElementId" : "pst",
    "ranges" : [ {
      "min" : 1,
      "max" : 7,
      "rangeType" : "absolute"
    }, {
      "min" : -3,
      "max" : 3,
      "rangeType" : "relativeToInitialNetwork"
    } ]
  }, {
    "id" : "pstRange2Id",
    "name" : "pstRange2Name",
    "operator" : "RTE",
    "onConstraintUsageRules" : [ {
      "instant" : "preventive",
      "cnecId" : "cnec3prevId"
    } ],
    "networkElementId" : "pst2",
    "groupId" : "group-1-pst",
    "ranges" : [ {
      "min" : 1,
      "max" : 7,
      "rangeType" : "absolute"
    }, {
      "min" : -3,
      "max" : 3,
      "rangeType" : "relativeToInitialNetwork"
    } ]
  }, {
    "id" : "pstRange3Id",
    "name" : "pstRange3Name",
    "operator" : "RTE",
    "onConstraintUsageRules" : [ {
      "instant" : "curative",
      "cnecId" : "angleCnecId"
    } ],
    "networkElementId" : "pst3",
    "groupId" : "group-3-pst",
    "activationCost": 0.0,
    "variationCosts": {
      "up": 0.0,
      "down": 0.0
    },
    "ranges" : [ {
      "min" : 1,
      "max" : 7,
      "rangeType" : "absolute"
    }, {
      "min" : -3,
      "max" : 3,
      "rangeType" : "relativeToInitialNetwork"
    } ]
  },{
    "id" : "pstRange4Id",
    "name" : "pstRange4Name",
    "operator" : "RTE",
    "onConstraintUsageRules" : [ {
      "instant" : "curative",
      "cnecId" : "voltageCnecId"
    } ],
    "networkElementId" : "pst4",
    "groupId" : "group-3-pst",
    "ranges" : [ {
      "min" : -2,
      "max" : 7,
      "rangeType" : "absolute"
    }, {
      "min" : -1,
      "max" : 4,
      "rangeType" : "relativeToPreviousTimeStep"
    } ]
  } ],
  "hvdcRangeActions" : [ {
    "id" : "hvdcRange1Id",
    "name" : "hvdcRange1Name",
    "operator" : "RTE",
    "speed" : 20,
    "onInstantUsageRules" : [ {
      "instant" : "preventive"
    } ],
    "networkElementId" : "hvdc",
    "ranges" : [ {
      "min" : -1000.0,
      "max" : 1000.0,
      "rangeType" : "absolute"
    } ]
  }, {
    "id" : "hvdcRange2Id",
    "name" : "hvdcRange2Name",
    "operator" : "RTE",
    "activationCost": 100.0,
    "variationCosts": {
      "down": 500.0
    },
    "onConstraintUsageRules" : [ {
      "instant" : "preventive",
      "cnecId" : "cnec3curId"
    } ],
    "networkElementId" : "hvdc2",
    "groupId" : "group-1-hvdc",
    "ranges" : [ {
      "min" : -1000.0,
      "max" : 1000.0,
      "rangeType" : "absolute"
    } ]
  } ],
  "injectionRangeActions" : [ {
    "id" : "injectionRange1Id",
    "name" : "injectionRange1Name",
    "operator" : null,
    "speed" : 30,
    "activationCost": 800.0,
    "variationCosts": {
      "up": 2000.0
    },
    "onContingencyStateUsageRules" : [ {
      "instant" : "curative",
      "contingencyId" : "contingency1Id"
    } ],
    "networkElementIdsAndKeys" : {
      "generator1Id" : 1.0,
      "generator2Id" : -1.0
    },
    "ranges" : [ {
      "min" : -500.0,
      "max" : 500.0,
      "rangeType" : "absolute"
    }, {
      "rangeType" : "relativeToPreviousInstant",
      "min" : -1000.0,
      "max" : 1000.0
    } ]
  } ],
  "counterTradeRangeActions" : [ {
    "id" : "counterTradeRange1Id",
    "name" : "counterTradeRange1Name",
    "operator" : null,
    "speed" : 30,
    "activationCost": 10000.0,
    "variationCosts": {
      "up": 15000.0,
      "down": 18000.0
    },
    "onInstantUsageRules" : [ {
      "instant" : "preventive"
    } ],
    "onConstraintUsageRules" : [ {
      "instant" : "preventive",
      "cnecId" : "cnec3curId"
    }, {
      "instant" : "curative",
      "cnecId" : "voltageCnecId"
    }, {
      "instant" : "curative",
      "cnecId" : "angleCnecId"
    } ],
    "onContingencyStateUsageRules" : [ {
      "instant" : "curative",
      "contingencyId" : "contingency1Id"
    } ],
    "area" : "BE",
    "initialNetPosition" : 500.0,
    "connectedAreas" : [ {
      "area" : "FR",
      "borderRanges" : [ {
        "min" : -500.0,
        "max" : 500.0,
        "rangeType" : "absolute"
      } ]
    }, {
      "area" : "DE",
      "borderRanges" : [ {
        "min" : -1000.0,
        "max" : 1000.0,
        "rangeType" : "absolute"
      } ]
    } ],
    "ranges" : [ {
      "min" : -500.0,
      "max" : 500.0,
      "rangeType" : "absolute"
    }, {
      "min" : -1000.0,
      "max" : 1000.0,
      "rangeType" : "absolute"
    } ]
  } ],
  "networkActions" : [ {
    "id" : "complexNetworkActionId",
    "name" : "complexNetworkActionName",
    "operator" : "RTE",
    "speed" : 40,
    "onInstantUsageRules" : [ {
      "instant" : "preventive"
    } ],
    "terminalsConnectionActions" : [ {
      "networkElementId" : "ne1Id",
      "actionType" : "close"
    } ],
    "phaseTapChangerTapPositionActions" : [ {
      "networkElementId" : "pst",
      "tapPosition" : 5
    } ]
  }, {
    "id" : "injectionSetpointRaId",
    "name" : "injectionSetpointRaName",
    "operator" : "RTE",
    "onConstraintUsageRules" : [ {
      "instant" : "auto",
      "cnecId" : "cnec3autoId"
    } ],
    "generatorActions" : [ {
      "networkElementId" : "injection",
      "activePowerValue" : 260.0
    }]
  }, {
